branch-defaults:
  default:
    environment: django-env
global:
  application_name: INTERNet
  branch: null
  default_ec2_keyname: null
  default_platform: python3.4
  default_region: us-east-1
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: null
  workspace_type: Application
